# Generated by Django 4.2.4 on 2023-08-19 23:55

import developers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_post_attachment_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=developers.models.user_post_attachment_path),
        ),
    ]
