# Generated by Django 4.2.4 on 2023-08-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_comment_parent_comment_userprofile_blocked_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
    ]
