# Generated by Django 4.2.4 on 2023-08-20 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '0010_remove_userprofile_relationships_userprofile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='user_blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
