# Generated by Django 4.2.4 on 2023-08-20 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '0011_userprofile_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_replies',
            field=models.ManyToManyField(blank=True, related_name='comment_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
