# Generated by Django 4.2.4 on 2023-08-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0013_alter_comment_comment_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_replies',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
