# Generated by Django 4.2.4 on 2023-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0016_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_one_on_one',
            field=models.BooleanField(default=True),
        ),
    ]
